name: GitHub-Profile-Summary-Cards

on:
  schedule: # Se ejecuta cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite ejecuci√≥n manual

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24f1tr/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: jxsem
